### PR TITLE
fix install script

### PR DESCRIPTION
**Pull request by victorskl**
- Capture 403 errors
- Check curl version is later than 7.76 (for --fail-with-body parameter)
- Check version of python3 is python3.10 or higher
- Find replace drop of libica version into shell function
- Bump libica to 2.3.0
- Revert folders to be mounted at the top of the scratch space
- Added analysis output option
- Workflow codes generated from github releases dont have datestamps
- start-cwl-wes now supports DATE_STR, UUID8, UUID16 and TIME_STR placeholders
- Fixed install script syntax closure

### CODE REVIEW

**Comment by victorskl** [comment]
Urgh! Habit. Abandoning.

I typically do `gh pr create -f` that pull against repo default set. Might be good, if you can set default branch to `dev`. But, leave to you.

**Comment by alexiswl** [comment]
See commentary here - https://stackoverflow.com/questions/44466618/default-branch-for-pull-request

**Comment by victorskl** [comment]
It probably on how you'd like to manage the stable build branch. Your choice, Alexis. 
Just old habit of mine. So no worries, I will learn/adapt to it.

**Comment by alexiswl** [comment]
Ah should be just `icav2 --version` now

**Comment by victorskl** [comment]
fixed

**Comment by victorskl** [comment]
now i'm looking at `v2-samplesheet-maker` repo, too! 👀

**Comment by alexiswl** [comment]
> It probably on how you'd like to manage the stable build branch. Your choice, Alexis.
> Just old habit of mine. So no worries, I will learn/adapt to it.

Switched to dev branch, otherwise issues need two PRs, one for dev and then another for main. 

Releases that contain more than ten issues fixed then cannot be linked to the second (main PR).  

Instead use dev branch as default branch. Issues will close as soon as they merge into dev, will attempt to pull dev into main more often

**Pull request closed without merging**
