### PR TITLE
requests library prints logs to stdout

### LINKED ISSUE #221: create workflow from github release prints errors to stdout
```
/home/cwl_ica_user/.icav2-cli-plugins/pyenv/lib/pypy3.9/site-packages/certifi/cacert.pem None
/etc/ssl/certs/ca-certificates.crt /etc/ssl/certs
```

### PR DESCRIPTION
**Pull request by alexiswl**
Relates to https://github.com/psf/requests/issues/6556

Resolves #221

### CODE REVIEW

**Comment by elliotwutingfeng** [comment]
I had a similar problem and managed to find the function in the `certifi` package that could be causing this erroneous output.

**Source:** https://github.com/elliotwutingfeng/tldextract/actions/runs/7442606795/job/20246275167

```python
 self = <ssl.SSLContext object at 0x00007fc6aae71d00>
cafile = '/home/runner/work/tldextract/tldextract/.tox/pypy310/lib/pypy3.10/site-packages/certifi/cacert.pem'
capath = None, cadata = None

    def load_verify_locations(self, cafile=None, capath=None, cadata=None):
        prev_errno = ffi.errno
        try:
            ffi.errno = 0
            if cadata is None:
                ca_file_type = -1
            else:
                if not isinstance(cadata, str):
                    ca_file_type = lib.SSL_FILETYPE_ASN1
                else:
                    ca_file_type = lib.SSL_FILETYPE_PEM
                    try:
                        cadata = cadata.encode('ascii')
                    except UnicodeEncodeError:
                        raise TypeError("cadata should be a ASCII string or a bytes-like object")
            if cafile is None and capath is None and cadata is None:
                raise TypeError("cafile and capath cannot be both omitted")
            # load from cadata
            if cadata is not None:
                buf = _str_to_ffi_buffer(cadata)
                self._add_ca_certs(buf, len(buf), ca_file_type)
    
            # load cafile or capath
            if cafile is not None or capath is not None:
>               print(cafile, capath)
```

**Comment by alexiswl** [comment]
Thanks @elliotwutingfeng, if it's any help, I resolved my issue when I moved my docker image away from pypy

https://github.com/umccr/cwl-ica-cli/pull/241/files
https://github.com/umccr/cwl-ica-cli/issues/240

**Comment by elliotwutingfeng** [comment]
In PyPy, the cause is likely due to the rogue print statement mentioned at https://github.com/pypy/pypy/issues/4009, which has since been resolved in PyPy **v7.3.14**.

**Comment by alexiswl** [comment]
Ah thank you very much for linking the resolved issue, I spent a long time on GitHub trying to figure out where the problem was coming from

**Pull request merged**
